apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 3000
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
